### ISSUE TITLE
[feature] Change your listview to a recyclerview

### ISSUE THREAD

**Issue by toonvanstrijp** [Limenie/Mobile-Client-Data-Transfer-Project#3]
I would suggest you changing you ListView to a RecyclerView.

The listview is a bit old dated and the recyclerview offers more flexibility and performance.

[https://medium.com/@manuaravindpta/what-is-the-difference-between-listview-and-recyclerview-bcd82c64ffbb](https://medium.com/@manuaravindpta/what-is-the-difference-between-listview-and-recyclerview-bcd82c64ffbb)

**Comment by alexphar** [comment]
That's a great suggestion. Thanks!

**Comment by indiciumSw** [comment]
In next version, yes.
